language: python
dist: xenial
sudo: required
python:
  - "3.5"
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python3
  - sudo apt-get install -y aria2
  - sudo apt-get install -y sound-theme-freedesktop     
  - sudo apt-get install -y libnotify-bin
  - sudo apt-get install -y libqt5svg5
  - sudo apt-get install -y python3-setuptools
  - sudo apt-get install -y python3-pip
  - sudo apt-get install -y python3-pyqt5
  - sudo apt-get install -y pulseaudio
  - sudo apt-get install -y python3-psutil
  - sudo pip3 install youtube-dl  
  - sudo pip3 install requests
  - sudo pip3 install setproctitle

script:
 - sudo python3 setup.py install
 - persepolis --version

after_success:
 - git clone https://github.com/transifex/transifex-client.git
 - cd transifex-client
 - python setup.py install
 - cd ../
 - sudo apt-get install  -y pyqt5-dev-tools
 - pylupdate5 -translate-function ui_tr resources/translation_files.pro
 - sudo echo $'[https://www.transifex.com]\nhostname = https://www.transifex.com\nusername = '"$TRANSIFEX_USER"$'\npassword = '"$TRANSIFEX_PASSWORD"$'\ntoken = '"$TRANSIFEX_API_TOKEN"$'\n' > ~/.transifexrc
 - tx push -s
