language: python
dist: trusty
sudo: required
python:
  - "3.4"
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y aria2 pulseaudio-utils libnotify-bin python3-pyqt5
install:
  - pip3 install requests
script:
 - bash install
 - man persepolis
