language: python
dist: trusty
sudo: required
python:
  - "3.4"
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y aria2 sound-theme-freedesktop libnotify-bin python3-pyqt5 libqt5svg5 python3-requests python3-setproctitle python3-setuptools
script:
 - sudo python3 setup.py install
